# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec4d980f81258f422b552ff7f9d314ffab64c1871b4818c42fdc434a36f4fad09df55db8d961b809f3c2262ba50fef6d1885188299e3120d8042917143bb3b7

test:
  secret_key_base: f2ab5d2bf0d4e78e19af0fb3fda52c4c3b671ff263cd01905c0bc324db2569efc1f203ead5e1b7b7f581e312fbab55773f5cfdd92c9b05154c253e8819521ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
